-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 21:16:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ResiliaDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ResiliaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ResiliaDB` DEFAULT CHARACTER SET utf8 ;
USE `ResiliaDB` ;

-- -----------------------------------------------------
-- Table `ResiliaDB`.`ALUNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`ALUNOS` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `curso_matriculado` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`CURSO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `carga_horaria` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`MATRICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`MATRICULA` (
  `ALUNOS_id` INT UNSIGNED NOT NULL,
  `CURSO_id` INT UNSIGNED NOT NULL,
  `situacao_matricula` VARCHAR(45) NOT NULL,
  `data_matricula` DATETIME NOT NULL,
  PRIMARY KEY (`ALUNOS_id`, `CURSO_id`),
  INDEX `fk_ALUNOS_has_CURSO_CURSO1_idx` (`CURSO_id` ASC),
  INDEX `fk_ALUNOS_has_CURSO_ALUNOS_idx` (`ALUNOS_id` ASC),
  CONSTRAINT `fk_ALUNOS_has_CURSO_ALUNOS`
    FOREIGN KEY (`ALUNOS_id`)
    REFERENCES `ResiliaDB`.`ALUNOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNOS_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_id`)
    REFERENCES `ResiliaDB`.`CURSO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`AREA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`DISCIPLINA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `carga_horaria` TINYINT NULL,
  `aulas_total` INT NULL,
  `CURSO_id` INT UNSIGNED NOT NULL,
  `CURSO_MODALIDADE_id` INT UNSIGNED NOT NULL,
  `AREA_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DISCIPLINA_CURSO1_idx` (`CURSO_id` ASC, `CURSO_MODALIDADE_id` ASC),
  INDEX `fk_DISCIPLINA_AREA1_idx` (`AREA_id` ASC),
  CONSTRAINT `fk_DISCIPLINA_CURSO1`
    FOREIGN KEY (`CURSO_id`)
    REFERENCES `ResiliaDB`.`CURSO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DISCIPLINA_AREA1`
    FOREIGN KEY (`AREA_id`)
    REFERENCES `ResiliaDB`.`AREA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`PROFESSOR` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`TURMA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_turma` VARCHAR(15) NULL,
  `DISCIPLINA_id` INT UNSIGNED NOT NULL,
  `DISCIPLINA_AREA_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TURMA_DISCIPLINA1_idx` (`DISCIPLINA_id` ASC, `DISCIPLINA_AREA_id` ASC),
  CONSTRAINT `fk_TURMA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_id`)
    REFERENCES `ResiliaDB`.`DISCIPLINA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`ALUNOS_has_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`ALUNOS_has_TURMA` (
  `ALUNOS_id` INT UNSIGNED NOT NULL,
  `TURMA_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ALUNOS_id`, `TURMA_id`),
  INDEX `fk_ALUNOS_has_TURMA_TURMA1_idx` (`TURMA_id` ASC),
  INDEX `fk_ALUNOS_has_TURMA_ALUNOS1_idx` (`ALUNOS_id` ASC),
  CONSTRAINT `fk_ALUNOS_has_TURMA_ALUNOS1`
    FOREIGN KEY (`ALUNOS_id`)
    REFERENCES `ResiliaDB`.`ALUNOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNOS_has_TURMA_TURMA1`
    FOREIGN KEY (`TURMA_id`)
    REFERENCES `ResiliaDB`.`TURMA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResiliaDB`.`PROFESSOR_has_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ResiliaDB`.`PROFESSOR_has_TURMA` (
  `PROFESSOR_id` INT UNSIGNED NOT NULL,
  `TURMA_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PROFESSOR_id`, `TURMA_id`),
  INDEX `fk_PROFESSOR_has_TURMA_TURMA1_idx` (`TURMA_id` ASC),
  INDEX `fk_PROFESSOR_has_TURMA_PROFESSOR1_idx` (`PROFESSOR_id` ASC),
  CONSTRAINT `fk_PROFESSOR_has_TURMA_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_id`)
    REFERENCES `ResiliaDB`.`PROFESSOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESSOR_has_TURMA_TURMA1`
    FOREIGN KEY (`TURMA_id`)
    REFERENCES `ResiliaDB`.`TURMA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
